src/AspnetRun.Web/ViewModels/CartViewModel.cs
using AspnetRun.Web.ViewModels.Base;
using System.Collections.Generic;

namespace AspnetRun.Web.ViewModels
{
    public class CartViewModel : BaseViewModel
    {
        public string UserName { get; set; }
        public List<CartItemViewModel> Items { get; set; } = new List<CartItemViewModel>();

        public decimal GrandTotal
        {
            get
            {
                decimal grandTotal = 0;
                foreach (var item in Items)
                {
                    grandTotal += item.TotalPrice;
                }

                return grandTotal;
            }
        }
    }
}

src/AspnetRun.Web/ViewModels/CompareViewModel.cs
using AspnetRun.Web.ViewModels.Base;
using System.Collections.Generic;

namespace AspnetRun.Web.ViewModels
{
    public class CompareViewModel : BaseViewModel
    {
        public string UserName { get; set; }
        public List<ProductViewModel> Items { get; set; } = new List<ProductViewModel>();
    }
}

src/AspnetRun.Web/ViewModels/ProductViewModel.cs
using AspnetRun.Web.ViewModels.Base;

namespace AspnetRun.Web.ViewModels
{
    public class ProductViewModel : BaseViewModel
    {
        public string Name { get; set; }
        public string Slug { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? UnitsInStock { get; set; }
        public double Star { get; set; }
        public int? CategoryId { get; set; }
        public CategoryViewModel Category { get; set; }
    }
}

src/AspnetRun.Web/ViewModels/WishlistViewModel.cs
using AspnetRun.Web.ViewModels.Base;
using System.Collections.Generic;

namespace AspnetRun.Web.ViewModels
{
    public class WishlistViewModel : BaseViewModel
    {
        public string UserName { get; set; }
        public List<ProductViewModel> Items { get; set; } = new List<ProductViewModel>();
    }
}

src/AspnetRun.Web/Pages/AboutUs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class AboutUsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/BestDeals.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class BestDealsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/BlogDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class BlogDetailModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/Blogs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class BlogsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    [Authorize]
    public class CartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/CheckOut.cshtml.cs
using System;
using System.Threading.Tasks;
using AspnetRun.Web.Interfaces;
using AspnetRun.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    [Authorize]
    public class CheckOutModel : PageModel
    {
        private readonly ICheckOutPageService _checkOutPageService;

        public CheckOutModel(ICheckOutPageService checkOutPageService)
        {
            _checkOutPageService = checkOutPageService ?? throw new ArgumentNullException(nameof(checkOutPageService));
        }

        public CartViewModel CartViewModel { get; set; } = new CartViewModel();

        [BindProperty]
        public OrderViewModel Order { get; set; }

        public async Task OnGetAsync()
        {
            CartViewModel = await _checkOutPageService.GetCart(User.Identity.Name);
        }        

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                CartViewModel = await _checkOutPageService.GetCart(User.Identity.Name);
                return Page();
            }
            
            await _checkOutPageService.CheckOut(Order, User.Identity.Name);
            return RedirectToPage("./OrderSubmitted");
        }        
    }
}

src/AspnetRun.Web/Pages/Compare.cshtml.cs
using System;
using System.Threading.Tasks;
using AspnetRun.Web.Interfaces;
using AspnetRun.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    [Authorize]
    public class CompareModel : PageModel
    {
        private readonly IComparePageService _comparePageService;
        private readonly ICartComponentService _cartComponentService;

        public CompareModel(IComparePageService comparePageService, ICartComponentService cartComponentService)
        {
            _comparePageService = comparePageService ?? throw new ArgumentNullException(nameof(comparePageService));
            _cartComponentService = cartComponentService ?? throw new ArgumentNullException(nameof(cartComponentService));
        }

        public CompareViewModel CompareViewModel { get; set; } = new CompareViewModel();

        public async Task OnGetAsync()
        {
            var userName = this.User.Identity.Name;
            CompareViewModel = await _comparePageService.GetCompare(userName);
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            await _comparePageService.AddToCart(User.Identity.Name, productId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromCompareAsync(int compareId, int productId)
        {
            await _comparePageService.RemoveItem(compareId, productId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveToCartAsync(int cartId, int cartItemId)
        {
            await _cartComponentService.RemoveItem(cartId, cartItemId);
            return RedirectToPage();
        }
    }
}

src/AspnetRun.Web/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/AspnetRun.Web/Pages/Faq.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class FaqModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/Feature.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class FeatureModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspnetRun.Web.Interfaces;
using AspnetRun.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IIndexPageService _indexPageService;
        private readonly ICartComponentService _cartComponentService;

        public IndexModel(IIndexPageService indexPageService, ICartComponentService cartComponentService)
        {
            _indexPageService = indexPageService ?? throw new ArgumentNullException(nameof(indexPageService));
            _cartComponentService = cartComponentService ?? throw new ArgumentNullException(nameof(cartComponentService));
        }

        public IEnumerable<ProductViewModel> ProductList { get; set; } = new List<ProductViewModel>();
        public CategoryViewModel CategoryModel { get; set; } = new CategoryViewModel();

        public async Task OnGetAsync()
        {
            ProductList = await _indexPageService.GetProducts();              
        }

        public async Task<IActionResult> OnPostRemoveToCartAsync(int cartId, int cartItemId)
        {
            await _cartComponentService.RemoveItem(cartId, cartItemId);
            return RedirectToPage();
        }
    }
}

src/AspnetRun.Web/Pages/OrderSubmitted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class OrderSubmittedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/ProductDetail.cshtml.cs
using System;
using System.Threading.Tasks;
using AspnetRun.Web.Interfaces;
using AspnetRun.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class ProductDetailModel : PageModel
    {
        private readonly IProductPageService _productPageService;
        private readonly ICartComponentService _cartComponentService;

        public ProductDetailModel(IProductPageService productPageService, ICartComponentService cartComponentService)
        {
            _productPageService = productPageService ?? throw new ArgumentNullException(nameof(productPageService));
            _cartComponentService = cartComponentService ?? throw new ArgumentNullException(nameof(cartComponentService));
        }

        public ProductViewModel Product { get; set; } = new ProductViewModel();
        
        public async Task OnGetAsync(string slug)
        {
            Product = await _productPageService.GetProductBySlug(slug);
            TempData["Slug"] = slug;
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _productPageService.AddToCart(User.Identity.Name, productId);            
            return RedirectToPage(new { slug = TempData["Slug"].ToString() });            
        }

        public async Task<IActionResult> OnPostAddToWishlistAsync(int productId)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _productPageService.AddToWishlist(User.Identity.Name, productId);
            return RedirectToPage(new { slug = TempData["Slug"].ToString() });
        }

        public async Task<IActionResult> OnPostAddToCompareAsync(int productId)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _productPageService.AddToCompare(User.Identity.Name, productId);
            return RedirectToPage(new { slug = TempData["Slug"].ToString() });
        }

        public async Task<IActionResult> OnPostRemoveToCartAsync(int cartId, int cartItemId)
        {
            await _cartComponentService.RemoveItem(cartId, cartItemId);
            return RedirectToPage(new { slug = TempData["Slug"].ToString() });
        }
    }
}

src/AspnetRun.Web/Pages/Products.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspnetRun.Web.Interfaces;
using AspnetRun.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class ProductsModel : PageModel
    {
        private readonly IProductPageService _productPageService;        
        private readonly ICartComponentService _cartComponentService; // due to every page has cart, we also inject cart view component service in order to catch post actions

        public ProductsModel(IProductPageService productPageService, ICartComponentService cartComponentService)
        {
            _productPageService = productPageService ?? throw new ArgumentNullException(nameof(productPageService));
            _cartComponentService = cartComponentService ?? throw new ArgumentNullException(nameof(cartComponentService));
        }

        public IEnumerable<ProductViewModel> ProductList { get; set; } = new List<ProductViewModel>();

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; } = string.Empty;

        public async Task OnGetAsync()
        {
            ProductList = await _productPageService.GetProducts(SearchTerm);
        }
        
        public async Task<IActionResult> OnPostAddToCartAsync(int productId)
        {
            if(!User.Identity.IsAuthenticated)
                return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _productPageService.AddToCart(User.Identity.Name, productId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddToWishlistAsync(int productId)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _productPageService.AddToWishlist(User.Identity.Name, productId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddToCompareAsync(int productId)
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToPage("./Account/Login", new { area = "Identity" });

            await _productPageService.AddToCompare(User.Identity.Name, productId);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveToCartAsync(int cartId, int cartItemId)
        {
            await _cartComponentService.RemoveItem(cartId, cartItemId);
            return RedirectToPage();
        }

    }
}

src/AspnetRun.Web/Pages/Store.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnetRun.Web.Pages
{
    public class StoreModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/AspnetRun.Web/Pages/Compare.cshtml
@page
@model AspnetRun.Web.Pages.CompareModel
@{
    ViewData["Title"] = "Compare";
}

<!-- Compare Page Start -->
<div class="page-section section mt-90 mb-90">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <!-- Compare Table -->
                <div class="compare-table table-responsive">
                    <table class="table mb-0">
                        <tbody>
                            <tr>
                                <td class="first-column">Product</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="product-image-title">
                                        <a asp-page="ProductDetail" asp-route-slug="@item.Slug" class="image"><img src="assets/images/product/@item.ImageFile" alt="Compare Product"></a>
                                        <a asp-page="ProductDetail" asp-route-slug="@item.Slug" class="category">@item.Category.Name</a>
                                        <a asp-page="ProductDetail" asp-route-slug="@item.Slug" class="title">@item.Name</a>
                                    </td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Description</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-desc"><p>@item.Summary</p></td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Price</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-price">$@item.UnitPrice</td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Color</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-color">Black</td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Stock</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-stock">
                                        @if (item.UnitsInStock > 0)
                                        {
                                            @: In Stock
                                        }
                                        else
                                        {
                                            @: Not Available
                                        }
                                    </td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Add to cart</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-addtocart">
                                        <form asp-page-handler="AddToCart" method="post">
                                            <a href="javascript:;" onclick="parentNode.submit();" class="add-to-cart"><i class="ti-shopping-cart"></i><span>ADD TO CART</span></a>
                                            <input type="hidden" asp-for="@item.Id" name="productId" />
                                        </form>
                                    </td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Delete</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-remove">
                                        <form asp-page-handler="removefromcompare" method="post">
                                            <button><i class="fa fa-trash-o"></i></button>
                                            <input type="hidden" asp-for="@Model.CompareViewModel.Id" name="compareId" />
                                            <input type="hidden" asp-for="@item.Id" name="productId" />
                                        </form>
                                    </td>
                                }

                            </tr>
                            <tr>
                                <td class="first-column">Rating</td>

                                @foreach (var item in Model.CompareViewModel.Items)
                                {
                                    <td class="pro-ratting">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star-o"></i>
                                    </td>
                                }

                            </tr>
                        </tbody>
                    </table>
                </div>



            </div>
        </div>
    </div>
</div>
<!-- Compare Page End -->

src/AspnetRun.Web/Pages/Feature.cshtml
@page
@model AspnetRun.Web.Pages.FeatureModel
@{
}

<!-- About Section Start -->
<div class="about-section section mt-90 mb-30">
    <div class="container">

        <div class="row">

            <!-- Feature Content -->
            <div class="feature-content col-lg-6 col-12 order-2 order-lg-1 mb-30">
                <h2><span>YOU CAN</span> CHOOSE US</h2>
                <h1>BECAUSE <span>WE ALWAYS PROVIDE</span> IMPORTANCE...</h1>
                <p>E&E provide how all this mistaken idea of denouncing pleasure and sing pain was born an will give you a complete account of the system, and expound the actual teachings of the eat explorer of the truth, the mer of human</p>
                <p>E&E provide how all this mistaken idea of denouncing pleasure and sing pain was born an will give you a complete account of the system, and expound the actual teachings of the eat explorer of the truth, the mer of human</p>
            </div>

            <!-- Feature Image -->
            <div class="col-lg-5 col-12 order-1 order-lg-2 ml-auto mb-30">
                <div class="feature-image"><img src="assets/images/about/feature-image.jpg" alt=""></div>
            </div>

        </div>

        <div class="row mb-30">

            <!-- About Feature -->
            <div class="about-feature col-lg-9 col-12">
                <div class="row">

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>FAST DELIVERY</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>QUALITY PRODUCT</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30 d-none d-lg-block"></div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>SECURE PAYMENT</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>MONEY BACK GUARNTEE</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>EASY ORDER TRACKING</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>FREE RETURN</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                    <div class="col-lg-4 col-md-6 col-12 mb-30">
                        <h4>24/7 SUPPORT</h4>
                        <p>E&E provide how all this mistaken dea of denouncing pleasure and sing </p>
                    </div>

                </div>
            </div>

        </div>

    </div>
</div><!-- About Section End -->

src/AspnetRun.Web/Pages/OrderSubmitted.cshtml
@page
@model AspnetRun.Web.Pages.OrderSubmittedModel
@{
}

<!-- Track Order Section Start -->
<div class="track-order-section section mt-90 mb-50">
    <div class="container">
        <div class="row align-items-center">

            <div class="track-order-title text-center col-12 mb-80">
                <h2>Your Order Submitted Successfully...</h2>
                <p>To track your order please go to Track Order page. This was give to you on your receipt and in the confirmation email you should have reveived</p>
            </div>
        </div>
    </div>
</div>
<!-- Track Order Section End -->

src/AspnetRun.Web/Pages/TrackOrder.cshtml
@page
@model AspnetRun.Web.Pages.TrackOrderModel
@{
}

<!-- Track Order Section Start -->
<div class="track-order-section section mt-90 mb-50">
    <div class="container">
        <div class="row align-items-center">

            <div class="track-order-title text-center col-12 mb-80">
                <h2>Track your order...</h2>
                <p>To track your order please enter your Order ID in the box below and press the “Track” button. This was give to you on your receipt and in the confirmation email you should have reveived</p>
            </div>

            <div class="col-lg-6 col-md-7 col-12 mb-40">
                <div class="track-order-form">
                    <form action="#">
                        <label for="order_id">Order ID</label>
                        <input type="text" id="order_id" placeholder="Find it in your order confirmation email">
                        <label for="billing_email">Billing Email Address</label>
                        <input type="email" id="billing_email" placeholder="Email you used during checkout">

                        <input type="submit" value="Track Order">
                    </form>
                </div>
            </div>

            <div class="col-lg-4 col-md-5 col-12 ml-auto mb-40">
                <div class="banner"><a href="#"><img src="assets/images/banner/banner-33.jpg" alt="Banner"></a></div>
            </div>

        </div>
    </div>
</div><!-- Track Order Section End -->

src/AspnetRun.Web/Pages/Wishlist.cshtml
@page
@model AspnetRun.Web.Pages.WishlistModel
@{
    ViewData["Title"] = "Wishlist";
}

<!-- Cart Page Start -->
<div class="page-section section mt-90 mb-90">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="cart-table table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="pro-thumbnail">Image</th>
                                <th class="pro-title">Product</th>
                                <th class="pro-price">Price</th>
                                <th class="pro-quantity">Quantity</th>
                                <th class="pro-subtotal">Total</th>
                                <th class="pro-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.WishlistViewModel.Items)
                            {
                                <tr>
                                    <td class="pro-thumbnail"><a asp-page="ProductDetail" asp-route-slug="@item.Slug"><img src="assets/images/product/@item.ImageFile" alt="Product"></a></td>
                                    <td class="pro-title"><a href="#">@item.Name</a></td>
                                    <td class="pro-price"><span>$@item.UnitPrice</span></td>
                                    <td class="pro-quantity"><div class="pro-qty"><input type="text" value="1"></div></td>

                                    <td class="pro-addtocart">
                                        <form asp-page-handler="addtocart" method="post">
                                            <button>add to cart</button>
                                            <input type="hidden" asp-for="@item.Id" name="productId" />
                                        </form>
                                    </td>

                                    <td class="pro-remove">
                                        <form asp-page-handler="removefromwishlist" method="post">
                                            <a href="javascript:;" onclick="parentNode.submit();"><i class="fa fa-trash-o"></i></a>
                                            <input type="hidden" asp-for="@Model.WishlistViewModel.Id" name="wishlistId" />
                                            <input type="hidden" asp-for="@item.Id" name="productId" />
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- Cart Page End -->